const minute = 60 * 1000

export const ELITE_MONSTERS = [
  { region: 'Dien', area: 'Northern Dien', level: 8, name: 'Screaming Wings', respawnMs: 15 * minute },
  { region: 'Dien', area: 'Northern Dien', level: 14, name: 'Outlaw Kaiser', respawnMs: 15 * minute },
  { region: 'Dien', area: 'Gray Ruins', level: 19, name: 'Suspicious Wizard', respawnMs: 15 * minute },
  { region: 'Dien', area: 'Gray Ruins', level: 23, name: 'Dark Apparition', respawnMs: 15 * minute },
  { region: 'Dien', area: 'Corrupted Basin', level: 30, name: 'Corrupted Shellbug', respawnMs: 10 * minute },
  { region: 'Dien', area: 'Corrupted Basin', level: 35, name: 'Brutal Butcher', respawnMs: 10 * minute },
  { region: 'Dien', area: 'Secret Laboratory', level: 40, name: 'Secret Creation', respawnMs: 15 * minute },
  { region: 'Dien', area: 'Secret Laboratory', level: 60, name: 'Magic Puppet', respawnMs: 15 * minute },
  { region: 'Dien', area: 'Secret Laboratory', level: 60, name: "Wizard's Pet", respawnMs: 15 * minute },
  { region: 'Lindris', area: 'Crescent Lake', level: 46, name: 'Angusto', respawnMs: 10 * minute },
  { region: 'Lindris', area: 'Crescent Lake', level: 46, name: 'Lamia Shaman', respawnMs: 10 * minute },
  { region: 'Lindris', area: 'Twilight Hill', level: 49, name: 'Ancient Thardus', respawnMs: 10 * minute },
  { region: 'Lindris', area: 'Twilight Hill', level: 54, name: 'Berserk Thardus', respawnMs: 10 * minute },
  { region: 'Lindris', area: 'Twilight Hill', level: 53, name: 'Charging Thardus', respawnMs: 15 * minute },
  { region: 'Ulan', area: 'Ulan Canyon', level: 57, name: 'Desert Golem', respawnMs: 15 * minute },
  { region: 'Ulan', area: 'Ulan Canyon', level: 58, name: 'Ancient Turtle', respawnMs: 15 * minute },
  { region: 'Ulan', area: 'Ulan Canyon', level: 59, name: 'Alarak', respawnMs: 15 * minute },
  { region: 'Ulan', area: "Protector's Ruins", level: 61, name: 'Protector of the Ruins', respawnMs: 15 * minute },
  { region: 'Ulan', area: "Protector's Ruins", level: 64, name: 'Black Hand', respawnMs: 15 * minute },
  { region: 'Ulan', area: "Protector's Ruins", level: 64, name: 'Ancient Protector', respawnMs: 15 * minute },
  { region: 'Ulan', area: 'Desert of the Screaming', level: 70, name: 'Black Wedge', respawnMs: 20 * minute },
  { region: 'Ulan', area: 'Desert of the Screaming', level: 70, name: 'Desert Protector', respawnMs: 20 * minute },
  { region: 'Ulan', area: 'Desert of the Screaming', level: 71, name: 'Intikam', respawnMs: 20 * minute },
  { region: 'Dungeons', area: 'Garbana Underground Waterway 1F', level: 98, name: "One-Eyed Kua'toa", respawnMs: 15 * minute },
  { region: 'Dungeons', area: 'Garbana Underground Waterway 1F', level: 98, name: "Roderick's Servant", respawnMs: 15 * minute },
  { region: 'Dungeons', area: 'Garbana Underground Waterway 2F', level: 108, name: 'Great Herculean Duvah', respawnMs: 15 * minute },
  { region: 'Dungeons', area: 'Garbana Underground Waterway 2F', level: 108, name: 'Twitching Fin', respawnMs: 15 * minute },
  { region: 'Dungeons', area: 'Garbana Underground Waterway 3F', level: 120, name: 'Bad Water Bragron', respawnMs: 15 * minute },
  { region: 'Dungeons', area: 'Garbana Underground Waterway 3F', level: 120, name: 'Corroded Scute Logban', respawnMs: 15 * minute },
  { region: 'Ulan', area: 'Lower Tomb of Tyriosa 1F', level: 75, name: 'Brood Mother', respawnMs: 15 * minute },
  { region: 'Ulan', area: 'Lower Tomb of Tyriosa 1F', level: 75, name: 'Decoy', respawnMs: 15 * minute },
  { region: 'Ulan', area: 'Lower Tomb of Tyriosa 2F', level: 87, name: 'Ghost Webber', respawnMs: 15 * minute },
  { region: 'Ulan', area: 'Lower Tomb of Tyriosa 2F', level: 87, name: 'Shadow Webber', respawnMs: 15 * minute },
  { region: 'Ulan', area: 'Lower Tomb of Tyriosa 3F', level: 103, name: 'Escort Leader Maximus', respawnMs: 15 * minute },
  { region: 'Ulan', area: 'Lower Tomb of Tyriosa 3F', level: 103, name: 'Fortune Teller Ariel', respawnMs: 15 * minute },
  { region: 'Ulan', area: 'Lower Tomb of Tyriosa 3F', level: 103, name: 'Priest Petroca', respawnMs: 15 * minute },
  { region: 'Serbis', area: 'Land of Glory', level: 78, name: 'Halfmoon Stone Turtle', respawnMs: 30 * minute },
  { region: 'Serbis', area: 'Land of Glory', level: 78, name: 'Sylandra', respawnMs: 30 * minute },
  { region: 'Serbis', area: 'Land of Glory', level: 83, name: 'Cobolt Blitz Captain', respawnMs: 30 * minute },
  { region: 'Serbis', area: 'Battlefield of Templar', level: 87, name: 'Forgotten Olive', respawnMs: 30 * minute },
  { region: 'Serbis', area: 'Battlefield of Templar', level: 93, name: "Deadman's Grow", respawnMs: 30 * minute },
  { region: 'Serbis', area: 'Battlefield of Templar', level: 93, name: 'Black Wings', respawnMs: 30 * minute },
  { region: 'Serbis', area: 'Plateau of Revolution', level: 92, name: 'Cassandra', respawnMs: 30 * minute },
  { region: 'Serbis', area: 'Plateau of Revolution', level: 94, name: 'Red Lizardman Patrol Captain', respawnMs: 30 * minute },
  { region: 'Serbis', area: 'Plateau of Revolution', level: 97, name: 'Mutated Scorpion', respawnMs: 30 * minute },
  { region: 'Serbis', area: 'Plateau of Revolution', level: 99, name: 'Berserk Higher Harpy', respawnMs: 30 * minute },
  { region: 'Serbis', area: 'Ruins of the War', level: 98, name: 'Lyrian', respawnMs: 30 * minute },
  { region: 'Serbis', area: 'Ruins of the War', level: 103, name: 'Durian', respawnMs: 30 * minute },
  { region: 'Serbis', area: 'Ruins of the War', level: 103, name: 'Infected Kukri', respawnMs: 30 * minute },
  { region: 'Serbis', area: 'Ruins of the War', level: 104, name: 'Straggler Brown', respawnMs: 30 * minute },
  { region: 'Serbis', area: 'Silvergrass Land', level: 105, name: 'Shaug High-ranking Wizard', respawnMs: 30 * minute },
  { region: 'Serbis', area: 'Silvergrass Land', level: 109, name: 'Shaug Blitz Captain', respawnMs: 30 * minute },
  { region: 'Serbis', area: 'Silvergrass Land', level: 110, name: 'Shaug Patrol Captain', respawnMs: 30 * minute },
  { region: 'Serbis', area: 'Silvergrass Land', level: 113, name: 'Veridon', respawnMs: 30 * minute },
  { region: 'Serbis', area: 'Barbas', level: 112, name: 'Restrained Soul', respawnMs: 30 * minute },
  { region: 'Serbis', area: 'Barbas', level: 114, name: 'Flame Wolf', respawnMs: 30 * minute },
  { region: 'Serbis', area: 'Barbas', level: 112, name: 'Giant Wyvern', respawnMs: 30 * minute },
  { region: 'Serbis', area: 'Barbas', level: 110, name: 'Red Lizardman Sniper Captain', respawnMs: 30 * minute },
  { region: 'Serbis', area: "Deadman's Land District 1F", level: 97, name: 'Elder Lich', respawnMs: 30 * minute },
  { region: 'Serbis', area: "Deadman's Land District 1F", level: 97, name: "Catena's Eye", respawnMs: 30 * minute },
  { region: 'Serbis', area: "Deadman's Land District 2F", level: 105, name: 'Elder Scorpius', respawnMs: 30 * minute },
  { region: 'Serbis', area: "Deadman's Land District 2F", level: 105, name: "Catena's Servant", respawnMs: 30 * minute },
  { region: 'Serbis', area: "Deadman's Land District 2F", level: 105, name: "Catena's Cry", respawnMs: 30 * minute },
  { region: 'Serbis', area: "Deadman's Land District 3F", level: 118, name: "Catena's Ego", respawnMs: 30 * minute },
  { region: 'Serbis', area: "Deadman's Land District 3F", level: 118, name: "Catena's Rage", respawnMs: 30 * minute },
  { region: 'Serbis', area: "Deadman's Land District 3F", level: 118, name: "Catena's Sorrow", respawnMs: 30 * minute },
]
